export const WEB_HTML = `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="dark"><title>Solver</title><link rel="stylesheet" href="/app.css"></head>
<body><main><section id="auth-view" class="auth"><div class="card"><h1>Ask Solver from anywhere.</h1><p>Sign in through your organization's identity provider to start a private assistant session.</p><button class="primary" id="login">Continue with OIDC</button><p class="error" id="auth-error"></p></div></section>
<section id="chat-view" class="chat" hidden><button class="admin-link" id="admin-prompt" hidden>System prompt</button><div class="messages" id="messages" aria-live="polite"></div><form class="composer" id="composer"><textarea id="prompt" rows="1" maxlength="32000" placeholder="Message Solver..." aria-label="Message" required></textarea><button class="send" aria-label="Send">↑</button></form></section>
<section id="settings-view" class="settings" hidden><header><div><em id="settings-eyebrow">ADMINISTRATION</em><h1>OIDC settings</h1></div></header><form id="settings-form"><div class="notice" id="setup-notice" hidden>Complete setup before exposing this service publicly. The first successful save closes unauthenticated setup access.</div><div class="notice">The client secret is encrypted at rest and is never returned by the API. Leave it blank to keep the stored value.</div><label class="check"><input type="checkbox" name="enabled"> Enable OIDC login</label><label>Issuer URL<input name="issuerUrl" type="url" required placeholder="https://id.example.com"></label><label>Client ID<input name="clientId" required autocomplete="off"></label><label>Client secret<input name="clientSecret" type="password" autocomplete="new-password"><small id="secret-state"></small></label><label>Redirect URI<input name="redirectUri" type="url" required placeholder="https://solver.example.com/auth/callback"><small>Must use the path /auth/callback.</small></label><label>Scopes<input name="scopes" required value="openid profile email"></label><label>Allowed chat subjects<input name="allowedSubjects" placeholder="subject-1, subject-2"><small>OIDC sub claims allowed to use the privileged assistant. Use * only for a fully trusted provider.</small></label><label>Administrator subjects<input name="adminSubjects" placeholder="admin-subject"><small>OIDC sub claims allowed to manage these settings. At least one is required during initial setup unless configured by environment.</small></label><label class="check"><input type="checkbox" name="automaticLogin"> Automatically redirect signed-out visitors</label><label>Post-logout redirect URI<input name="postLogoutRedirectUri" type="url" placeholder="https://solver.example.com/"></label><p><button class="primary">Save settings</button> <span id="settings-status"></span></p></form></section>
<section id="prompt-settings-view" class="settings" hidden><header><div><em>ADMINISTRATION</em><h1>System prompt</h1></div><button id="prompt-back">Back to chat</button></header><form id="prompt-settings-form"><div class="notice">This global prompt is loaded for every future Discord and web agent request. Runtime protocol and safety instructions are appended separately.</div><label>Effective global system prompt<textarea name="prompt" rows="16" maxlength="32000" required></textarea></label><small id="prompt-metadata"></small><p><button class="primary">Save prompt</button> <button type="button" id="prompt-reset">Reset to default</button> <span id="prompt-settings-status"></span></p></form></section></main><script src="/app.js" defer></script></body></html>`

export const WEB_CSS = `
@font-face{font-family:gg;src:url('/fonts/gg-sans-400.woff2')}@font-face{font-family:gg;src:url('/fonts/gg-sans-700.woff2');font-weight:700}:root{font-family:gg,system-ui;color:#dbdee1;background:#313338;--line:#3f4147;--muted:#949ba4}*{box-sizing:border-box}[hidden]{display:none!important}body{margin:0}button,input,textarea,select{font:inherit}.chat{height:100vh;display:grid;grid-template-rows:1fr auto;max-width:960px;margin:auto}.messages{overflow:auto;padding:24px 28px}.empty{height:100%;display:grid;place-items:center;color:var(--muted)}.message{display:grid;grid-template-columns:40px 1fr;gap:14px;padding:10px 0}.avatar{width:40px;height:40px;display:grid;place-items:center;border-radius:50%;background:#5865f2;font-weight:700}.user .avatar{background:#4e5058}.meta{display:flex;gap:8px;align-items:baseline}.meta time,.status,p,small{color:var(--muted)}.body{line-height:1.5;overflow-wrap:anywhere}.body pre,.body code{background:#2b2d31;border-radius:4px}.body pre{overflow:auto;padding:12px}.body code{padding:2px 4px}.body pre code{padding:0}.body a{color:#00a8fc}.body blockquote{border-left:3px solid var(--muted);margin-left:0;padding-left:12px}.embed{border-left:4px solid #5865f2;background:#2b2d31;padding:10px 12px;margin-top:8px}.component-button{display:inline-block;margin:8px 6px 0 0;color:#dbdee1}.composer{display:flex;align-items:flex-end;gap:8px;margin:0 28px 24px;padding:8px;background:#383a40;border-radius:8px}.composer textarea{flex:1;resize:none;min-height:40px;max-height:180px;padding:10px;border:0;outline:0;color:#dbdee1;background:transparent}.send,.primary{border:0;border-radius:6px;background:#5865f2;color:white;font-weight:700;cursor:pointer}.send{width:40px;height:40px;font-size:18px}.auth{min-height:100vh;display:grid;place-items:center;padding:24px}.card{max-width:520px;padding:32px}.card h1{font-size:32px}.primary{padding:10px 14px}.error{color:#f23f42}.settings{min-height:100vh;max-width:800px;margin:auto;padding:28px}.settings form{display:grid;gap:16px}.settings form>label:not(.check){display:grid;gap:6px}.settings input,.settings select{padding:9px;color:#dbdee1;background:#2b2d31;border:1px solid var(--line);border-radius:4px}.check{display:flex;gap:8px}.notice{padding:12px;background:#2b2d31;color:var(--muted)}@media(max-width:600px){.messages{padding:16px 14px}.composer{margin:0 12px 12px}.settings{padding:20px}}

.component-button{display:inline-flex;align-items:center;gap:6px;padding:7px 12px;border:0;border-radius:3px;color:#fff!important;background:#4e5058;font-weight:500;line-height:20px;text-decoration:none;cursor:pointer}.component-button.primary{background:#5865f2}.component-button.success{background:#248046}.component-button.danger{background:#da373c}.component-button:hover:not(:disabled){filter:brightness(.9)}.component-button:disabled,.component-button[aria-disabled=true]{opacity:.5;cursor:not-allowed}.component-emoji{width:20px;height:20px;object-fit:contain}.admin-link{position:fixed;right:20px;top:16px;z-index:1}.settings header{display:flex;align-items:center;justify-content:space-between;gap:16px}.settings textarea{min-height:320px;resize:vertical}
`

export const WEB_JS = String.raw`
const $=s=>document.querySelector(s);let state={session:null,streaming:false};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function md(value){let s=esc(value).replace(/@@CODE\d+@@/g,''),blocks=[],tick=String.fromCharCode(96);s=s.replace(new RegExp(tick+'{3}(?:\\w+)?\\n?([\\s\\S]*?)'+tick+'{3}','g'),(_,x)=>{blocks.push('<pre><code>'+x+'</code></pre>');return '@@CODE'+(blocks.length-1)+'@@'});s=s.replace(new RegExp(tick+'([^'+tick+']+)'+tick,'g'),'<code>$1</code>').replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>').replace(/__([^_]+)__/g,'<strong>$1</strong>').replace(/\*([^*]+)\*/g,'<em>$1</em>').replace(/^###? (.+)$/gm,'<h3>$1</h3>').replace(/^# (.+)$/gm,'<h2>$1</h2>').replace(/^&gt; (.+)$/gm,'<blockquote>$1</blockquote>').replace(/\[([^\]]+)\]\((https?:\/\/[^\s)]+)\)/g,'<a href="$2" target="_blank" rel="noopener noreferrer">$1</a>').replace(/(^|\s)(https?:\/\/[^\s<]+)/g,'$1<a href="$2" target="_blank" rel="noopener noreferrer">$2</a>').replace(/\n/g,'<br>');return s.replace(/@@CODE(\d+)@@/g,(_,i)=>blocks[Number(i)])}
function embed(e){let color=Number.isInteger(e.color)?'#'+e.color.toString(16).padStart(6,'0'):'#5865f2';return '<div class="embed" style="border-color:'+color+'">'+(e.author?.name?'<small>'+esc(e.author.name)+'</small>':'')+(e.title?'<h3>'+esc(e.title)+'</h3>':'')+(e.description?'<div>'+md(e.description)+'</div>':'')+(Array.isArray(e.fields)?e.fields.map(f=>'<p><strong>'+esc(f.name)+'</strong><br>'+md(f.value)+'</p>').join(''):'')+(e.footer?.text?'<footer>'+esc(e.footer.text)+'</footer>':'')+'</div>'}
function componentEmoji(e){if(!e||typeof e!=='object')return '';let name=esc(e.name||'');if(e.id&&/^\d+$/.test(String(e.id)))return '<img class="component-emoji" src="https://cdn.discordapp.com/emojis/'+esc(e.id)+'.webp?size=40" alt="'+name+'">';return name?'<span aria-hidden="true">'+name+'</span>':''}
function buttonComponent(c){let label=componentEmoji(c.emoji)+esc(c.label||(!c.emoji?'Action':'')),style=['','primary','secondary','success','danger','link'][c.style]||'secondary',disabled=c.disabled===true;if(c.url){if(disabled)return '<span class="component-button '+style+'" aria-disabled="true">'+label+'</span>';return '<a class="component-button '+style+'" href="'+esc(c.url)+'" target="_blank" rel="noopener noreferrer">'+label+'</a>'}if(typeof c.custom_id==='string')return '<button type="button" class="component-button '+style+'" data-component-kind="button" data-custom-id="'+esc(c.custom_id)+'"'+(disabled?' disabled':'')+'>'+label+'</button>';return '<button type="button" class="component-button '+style+'" disabled>'+label+'</button>'}
function components(items){if(!Array.isArray(items))return '';return items.map(c=>{if(!c||typeof c!=='object')return '';if(c.type===10&&typeof c.content==='string')return '<div>'+md(c.content)+'</div>';if(c.type===14)return '<hr>';if(c.type===2)return buttonComponent(c);return components(c.components||c.items)}).join('')}
function payload(raw){let p=raw;if(typeof raw==='string'){try{p=JSON.parse(raw)}catch{return md(raw)}}if(!p||typeof p!=='object')return '';return(typeof p.content==='string'?md(p.content):'')+(Array.isArray(p.embeds)?p.embeds.map(embed).join(''):'')+components(p.components)}
function message(role,content,time=new Date(),id){let el=document.createElement('article');el.className='message '+role;if(id)el.id=id;el.innerHTML='<span class="avatar">'+(role==='user'?'Y':'S')+'</span><div><div class="meta"><strong>'+(role==='user'?'You':'Solver')+'</strong><time>'+new Date(time).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})+'</time></div><div class="body">'+(role==='assistant'?payload(content):md(content))+'</div></div>';$('#messages').append(el);$('#messages').scrollTop=$('#messages').scrollHeight;return el}
const empty=()=>'<div class="empty">No messages yet</div>';
async function api(path,opt={}){opt.headers={...(opt.body?{'Content-Type':'application/json'}:{}),...(state.session?.csrfToken?{'X-CSRF-Token':state.session.csrfToken}:{}),...opt.headers};let r=await fetch(path,opt);if(!r.ok){let m='Request failed';try{m=(await r.json()).error||m}catch{}throw new Error(m)}return r}
async function readUpdates(r,onUpdate){let reader=r.body.getReader(),decoder=new TextDecoder(),buffer='';while(true){let {done,value}=await reader.read();buffer+=decoder.decode(value||new Uint8Array(),{stream:!done});let lines=buffer.split('\n');buffer=lines.pop()||'';for(let line of lines){if(line)onUpdate(JSON.parse(line))}if(done)break}}
async function history(){let r=await api('/api/chat/history?session=default'),turns=await r.json();$('#messages').innerHTML=turns.length?'':empty();turns.forEach(t=>message(t.role,t.content))}
async function session(){let r=await fetch('/api/session');state.session=await r.json();let yes=!!state.session.user,setup=state.session.oidcSetupRequired;$('#auth-view').hidden=yes||setup;$('#chat-view').hidden=!yes;$('#settings-view').hidden=!setup;$('#prompt-settings-view').hidden=true;$('#admin-prompt').hidden=!state.session.user?.admin;$('#login').hidden=!state.session.oidcEnabled;$('#setup-notice').hidden=!setup;$('#settings-eyebrow').textContent=setup?'INITIAL SETUP':'ADMINISTRATION';if(setup){$('#settings-form').elements.enabled.checked=true;await settings();return}if(yes){try{await history()}catch(e){$('#messages').innerHTML='<div class="empty error">'+esc(e.message)+'</div>';$('#composer').hidden=true}}else if(state.session.automaticLogin&&state.session.oidcEnabled)location.href='/auth/login'}
async function settings(){try{let r=await api('/api/admin/oidc'),data=await r.json(),f=$('#settings-form');Object.entries(data||{}).forEach(([k,v])=>{let field=f.elements.namedItem(k);if(!field)return;if(field.type==='checkbox')field.checked=!!v;else if(k!=='hasClientSecret')field.value=v??''});$('#secret-state').textContent=data?.hasClientSecret?'A secret is stored.':''}catch(e){$('#settings-status').textContent=e.message}}
function renderPromptSetting(data){$('#prompt-settings-form').elements.prompt.value=data.prompt;$('#prompt-metadata').textContent=data.updatedAt?'Last updated '+new Date(data.updatedAt).toLocaleString()+' by '+data.updatedBy:(data.isDefault?'Using built-in default':'')}
async function openPromptSettings(){try{let r=await api('/api/admin/system-prompt'),data=await r.json();renderPromptSetting(data);$('#chat-view').hidden=true;$('#prompt-settings-view').hidden=false;$('#prompt-settings-status').textContent=''}catch(e){$('#messages').innerHTML='<div class="empty error">'+esc(e.message)+'</div>'}}
$('#composer').addEventListener('submit',async e=>{e.preventDefault();if(state.streaming)return;let prompt=$('#prompt').value.trim();if(!prompt)return;$('#prompt').value='';$('#prompt').style.height='auto';if(prompt==='/clear'){try{await api('/api/chat/clear',{method:'POST',body:JSON.stringify({sessionName:'default'})});await history()}catch(err){$('#messages').innerHTML='<div class="empty error">'+esc(err.message)+'</div>'}return}state.streaming=true;$('#messages .empty')?.remove();message('user',prompt);let pending=message('assistant','',new Date(),'pending');pending.querySelector('.body').innerHTML='<span class="status">Starting assistant...</span>';try{let body={prompt,sessionName:'default'},r=await api('/api/chat',{method:'POST',body:JSON.stringify(body)});await readUpdates(r,update=>pending.querySelector('.body').innerHTML=update.error?'<span class="status error">'+esc(update.error)+'</span>':payload(update.payload))}catch(err){pending.querySelector('.body').innerHTML='<span class="status error">'+esc(err.message)+'</span>'}finally{state.streaming=false;pending.removeAttribute('id')}});
$('#messages').addEventListener('click',async e=>{let button=e.target.closest('button[data-component-kind="button"]');if(!button||button.disabled)return;let body=button.closest('.body'),buttons=body.querySelectorAll('button[data-component-kind]');buttons.forEach(item=>item.disabled=true);try{let r=await api('/api/interactions/components',{method:'POST',body:JSON.stringify({customId:button.dataset.customId})});await readUpdates(r,update=>body.innerHTML=update.error?'<span class="status error">'+esc(update.error)+'</span>':payload(update.payload))}catch(err){body.insertAdjacentHTML('beforeend','<div class="status error">'+esc(err.message)+'</div>');buttons.forEach(item=>item.disabled=false)}});
$('#prompt').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();$('#composer').requestSubmit()}});$('#prompt').addEventListener('input',e=>{e.target.style.height='auto';e.target.style.height=Math.min(e.target.scrollHeight,180)+'px'});$('#login').onclick=()=>location.href='/auth/login';
$('#admin-prompt').onclick=openPromptSettings;$('#prompt-back').onclick=()=>{$('#prompt-settings-view').hidden=true;$('#chat-view').hidden=false};
$('#prompt-settings-form').addEventListener('submit',async e=>{e.preventDefault();try{let prompt=e.target.elements.prompt.value,r=await api('/api/admin/system-prompt',{method:'PUT',body:JSON.stringify({prompt})}),data=await r.json();renderPromptSetting(data);$('#prompt-settings-status').textContent='Saved'}catch(err){$('#prompt-settings-status').textContent=err.message}});
$('#prompt-reset').onclick=async()=>{try{let r=await api('/api/admin/system-prompt/reset',{method:'POST'}),data=await r.json();renderPromptSetting(data);$('#prompt-settings-status').textContent='Reset to default'}catch(err){$('#prompt-settings-status').textContent=err.message}};
$('#settings-form').addEventListener('submit',async e=>{e.preventDefault();let f=e.target,data=Object.fromEntries(new FormData(f));data.enabled=f.elements.enabled.checked;data.automaticLogin=f.elements.automaticLogin.checked;try{let r=await api('/api/admin/oidc',{method:'PUT',body:JSON.stringify(data)}),saved=await r.json();$('#settings-status').textContent='Saved';$('#secret-state').textContent=saved.hasClientSecret?'A secret is stored.':'';if(state.session.oidcSetupRequired)await session()}catch(err){$('#settings-status').textContent=err.message}});session().catch(e=>$('#auth-error').textContent=e.message);
`
