export const WEB_HTML = `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="dark"><title>Solver</title><link rel="stylesheet" href="/app.css"></head>
<body><main><section id="auth-view" class="auth"><div class="card"><h1>Ask Solver from anywhere.</h1><p>Sign in through your organization's identity provider to start a private assistant session.</p><button class="primary" id="login">Continue with OIDC</button><p class="error" id="auth-error"></p></div></section>
<section id="chat-view" class="chat" hidden><header class="control-bar"><label><span>Session</span><select id="session-select" aria-label="Session"><option value="default">default</option><option value="">+ New session</option></select></label><label><span>Model</span><input id="model-select" list="model-options" aria-label="Model" autocomplete="off"><datalist id="model-options"></datalist></label><label><span>Reasoning</span><select id="effort" aria-label="Reasoning effort"><option value="none">None</option><option value="minimal">Minimal</option><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option><option value="xhigh">Extra high</option></select></label><label class="token-control"><span>Max tokens <output id="max-tokens-value">4096</output></span><input id="max-tokens" type="range" min="256" max="16384" step="256" value="4096" aria-label="Maximum tokens"></label><button class="admin-link" id="admin-prompt" hidden>System prompts</button></header><div class="message-pane"><div class="messages" id="messages" aria-live="polite"></div><button class="jump-bottom" id="jump-bottom" type="button" hidden>Latest messages ↓</button></div><form class="composer" id="composer"><textarea id="prompt" rows="1" maxlength="32000" placeholder="Message Solver..." aria-label="Message" required></textarea><button class="cancel" id="cancel-run" type="button" hidden>Cancel</button><button class="send" aria-label="Send">↑</button></form></section>
<section id="settings-view" class="settings" hidden><header><div><em id="settings-eyebrow">ADMINISTRATION</em><h1>OIDC settings</h1></div></header><form id="settings-form"><div class="notice" id="setup-notice" hidden>Complete setup before exposing this service publicly. The first successful save closes unauthenticated setup access.</div><div class="notice">The client secret is encrypted at rest and is never returned by the API. Leave it blank to keep the stored value.</div><label class="check"><input type="checkbox" name="enabled"> Enable OIDC login</label><label>Issuer URL<input name="issuerUrl" type="url" required placeholder="https://id.example.com"></label><label>Client ID<input name="clientId" required autocomplete="off"></label><label>Client secret<input name="clientSecret" type="password" autocomplete="new-password"><small id="secret-state"></small></label><label>Redirect URI<input name="redirectUri" type="url" required placeholder="https://solver.example.com/auth/callback"><small>Must use the path /auth/callback.</small></label><label>Scopes<input name="scopes" required value="openid profile email"></label><label>Allowed chat subjects<input name="allowedSubjects" placeholder="subject-1, subject-2"><small>OIDC sub claims allowed to use the privileged assistant. Use * only for a fully trusted provider.</small></label><label>Administrator subjects<input name="adminSubjects" placeholder="admin-subject"><small>Optional compatibility list whose subjects also receive chat access. Every authenticated identity can manage settings.</small></label><label class="check"><input type="checkbox" name="automaticLogin"> Automatically redirect signed-out visitors</label><label>Post-logout redirect URI<input name="postLogoutRedirectUri" type="url" placeholder="https://solver.example.com/"></label><p><button class="primary">Save settings</button> <span id="settings-status"></span></p></form></section>
<section id="prompt-settings-view" class="settings" hidden><header><div><em>AGENT SETTINGS</em><h1>System prompts</h1></div><button id="prompt-back">Back to chat</button></header><form id="prompt-settings-form"><div class="notice">This permanent global prompt applies to every Discord and Web UI session. Runtime protocol and safety instructions are appended separately.</div><label>Global system prompt<textarea name="prompt" rows="12" maxlength="32000" required></textarea></label><small id="prompt-metadata"></small><p><button class="primary">Save global prompt</button> <button type="button" id="prompt-reset">Reset global default</button> <span id="prompt-settings-status"></span></p></form><form id="session-prompt-settings-form"><div class="notice">These persistent instructions apply only to session <strong id="session-prompt-name"></strong>, in addition to the global prompt.</div><label>Session system prompt<textarea name="prompt" rows="10" maxlength="32000" placeholder="No additional instructions for this session"></textarea></label><small id="session-prompt-metadata"></small><p><button class="primary">Save session prompt</button> <button type="button" id="session-prompt-reset">Remove session prompt</button> <span id="session-prompt-settings-status"></span></p></form></section></main><dialog id="interaction-modal"><form method="dialog" id="interaction-modal-form"><header><h2 id="interaction-modal-title"></h2><button type="button" class="modal-close" aria-label="Close">×</button></header><div id="interaction-modal-fields"></div><p class="modal-error" aria-live="polite"></p><footer><button type="button" class="modal-cancel">Cancel</button><button class="primary" value="submit">Submit</button></footer></form></dialog><script src="/app.js" defer></script></body></html>`

export const WEB_CSS = `
@font-face{font-family:gg;src:url('/fonts/gg-sans-400.woff2')}@font-face{font-family:gg;src:url('/fonts/gg-sans-700.woff2');font-weight:700}:root{font-family:gg,system-ui;color:#dbdee1;background:#313338;--line:#3f4147;--muted:#949ba4}*{box-sizing:border-box}[hidden]{display:none!important}body{margin:0}button,input,textarea,select{font:inherit}.chat{height:100vh;display:grid;grid-template-rows:1fr auto;max-width:960px;margin:auto}.messages{overflow:auto;padding:24px 28px}.empty{height:100%;display:grid;place-items:center;color:var(--muted)}.message{display:grid;grid-template-columns:40px 1fr;gap:14px;padding:10px 0}.avatar{width:40px;height:40px;display:grid;place-items:center;border-radius:50%;background:#5865f2;font-weight:700}.user .avatar{background:#4e5058}.meta{display:flex;gap:8px;align-items:baseline}.meta time,.status,p,small{color:var(--muted)}.body{line-height:1.5;overflow-wrap:anywhere}.body pre,.body code{background:#2b2d31;border-radius:4px}.body pre{overflow:auto;padding:12px}.body code{padding:2px 4px}.body pre code{padding:0}.body a{color:#00a8fc}.body blockquote{border-left:3px solid var(--muted);margin-left:0;padding-left:12px}.embed{border-left:4px solid #5865f2;background:#2b2d31;padding:10px 12px;margin-top:8px}.component-button{display:inline-block;margin:8px 6px 0 0;color:#dbdee1}.composer{display:flex;align-items:flex-end;gap:8px;margin:0 28px 24px;padding:8px;background:#383a40;border-radius:8px}.composer textarea{flex:1;resize:none;min-height:40px;max-height:180px;padding:10px;border:0;outline:0;color:#dbdee1;background:transparent}.send,.primary{border:0;border-radius:6px;background:#5865f2;color:white;font-weight:700;cursor:pointer}.send{width:40px;height:40px;font-size:18px}.auth{min-height:100vh;display:grid;place-items:center;padding:24px}.card{max-width:520px;padding:32px}.card h1{font-size:32px}.primary{padding:10px 14px}.error{color:#f23f42}.settings{min-height:100vh;max-width:800px;margin:auto;padding:28px}.settings form{display:grid;gap:16px}.settings form>label:not(.check){display:grid;gap:6px}.settings input,.settings select{padding:9px;color:#dbdee1;background:#2b2d31;border:1px solid var(--line);border-radius:4px}.check{display:flex;gap:8px}.notice{padding:12px;background:#2b2d31;color:var(--muted)}@media(max-width:600px){.messages{padding:16px 14px}.composer{margin:0 12px 12px}.settings{padding:20px}}

.component-button{display:inline-flex;align-items:center;gap:6px;padding:7px 12px;border:0;border-radius:3px;color:#fff!important;background:#4e5058;font-weight:500;line-height:20px;text-decoration:none;cursor:pointer}.component-button.primary{background:#5865f2}.component-button.success{background:#248046}.component-button.danger{background:#da373c}.component-button:hover:not(:disabled){filter:brightness(.9)}.component-button:disabled,.component-button[aria-disabled=true]{opacity:.5;cursor:not-allowed}.component-emoji{width:20px;height:20px;object-fit:contain}.admin-link{position:fixed;right:20px;top:16px;z-index:1}.settings header{display:flex;align-items:center;justify-content:space-between;gap:16px}.settings textarea{min-height:320px;resize:vertical}
.admin-link{position:fixed;right:20px;top:16px;z-index:1}.settings header{display:flex;align-items:center;justify-content:space-between;gap:16px}.settings textarea{min-height:320px;resize:vertical}.component-row{display:flex;flex-wrap:wrap;gap:8px;margin-top:8px}.component-button{border:0;border-radius:4px;padding:8px 14px;background:#4e5058;color:#fff;text-decoration:none;cursor:pointer}.component-button.primary{background:#5865f2}.component-button.success{background:#248046}.component-button.danger{background:#da373c}.component-button:disabled,.component-select:disabled,.entity-select input:disabled{cursor:not-allowed;opacity:.55}.component-button.pending::after{content:' …'}.component-select{width:min(100%,400px);min-height:40px;padding:8px 10px;border:1px solid #1e1f22;border-radius:4px;background:#1e1f22;color:#dbdee1}.entity-select{display:flex;width:min(100%,480px);gap:6px}.entity-select input{flex:1;min-width:100px;padding:8px 10px;border:1px solid #1e1f22;border-radius:4px;background:#1e1f22;color:#dbdee1}.component-fallback{margin-top:8px;padding:8px 10px;border:1px dashed #5c5e66;border-radius:4px;color:var(--muted)}.interaction-status{margin-top:6px}.component-container{border:1px solid var(--line);border-radius:8px;padding:4px 10px;margin-top:8px}dialog{width:min(560px,calc(100% - 32px));max-height:calc(100vh - 32px);overflow:auto;border:1px solid var(--line);border-radius:8px;padding:0;background:#313338;color:#dbdee1;box-shadow:0 18px 60px #0008}dialog::backdrop{background:#0009}#interaction-modal-form{padding:20px}#interaction-modal-form header,#interaction-modal-form footer{display:flex;align-items:center;justify-content:space-between;gap:12px}#interaction-modal-form h2{margin:0}.modal-close{border:0;background:transparent;color:var(--muted);font-size:24px;cursor:pointer}.modal-field{display:grid;gap:6px;margin:18px 0}.modal-field>span{font-weight:700}.modal-field input[type=text],.modal-field textarea{width:100%;padding:10px;border:1px solid #1e1f22;border-radius:4px;background:#1e1f22;color:#dbdee1}.modal-field textarea{resize:vertical}.modal-options{display:grid;gap:8px}.modal-option{display:flex;align-items:flex-start;gap:8px;font-weight:400}.modal-error{min-height:20px;color:#f23f42}#interaction-modal-form footer{justify-content:flex-end}.modal-cancel{border:0;background:transparent;color:#dbdee1;cursor:pointer}@media(max-width:600px){.messages{padding:16px}.composer{margin:0 12px 12px}.message{grid-template-columns:32px 1fr}.avatar{width:32px;height:32px}.entity-select{flex-direction:column}}
.chat{grid-template-rows:auto 1fr auto}.control-bar{display:flex;align-items:end;gap:10px;overflow-x:auto;padding:12px 28px;border-bottom:1px solid var(--line);background:#2b2d31}.control-bar label{display:grid;flex:0 0 auto;gap:4px}.control-bar label>span{font-size:12px;color:var(--muted)}.control-bar select,.control-bar input{height:34px;border:1px solid var(--line);border-radius:5px;padding:6px 9px;background:#1e1f22;color:#dbdee1}.control-bar select{min-width:140px}.control-bar #model-select{width:210px}.control-bar .token-control{width:190px}.control-bar input[type=range]{width:100%;padding:0;accent-color:#5865f2}.control-bar output{color:#dbdee1}.control-bar .admin-link{position:static;flex:0 0 auto;margin-left:auto;height:34px}@media(max-width:600px){.control-bar{padding:10px 14px}.messages{padding:18px 14px}.composer{margin:0 14px 14px}}
.message-pane{position:relative;min-height:0}.messages{height:100%;min-height:0;scroll-behavior:smooth}.jump-bottom{position:absolute;left:50%;bottom:16px;z-index:2;transform:translateX(-50%);padding:8px 14px;border:1px solid var(--line);border-radius:18px;background:#2b2d31;color:#dbdee1;box-shadow:0 4px 14px #0006;cursor:pointer}.jump-bottom:hover{background:#383a40}
.body ul{margin:4px 0;padding-left:24px}.body .subtext{font-size:12px;color:var(--muted)}
.settings #session-prompt-settings-form{margin-top:28px;padding-top:28px;border-top:1px solid var(--line)}
.cancel{height:40px;padding:0 12px;border:0;border-radius:6px;background:#da373c;color:#fff;font-weight:700;cursor:pointer}
`

export const WEB_MARKDOWN_JS = String.raw`
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function md(value){let s=esc(value).replace(/@@CODE\d+@@/g,''),blocks=[],tick=String.fromCharCode(96);s=s.replace(new RegExp(tick+'{3}(?:\\w+)?\\n?([\\s\\S]*?)'+tick+'{3}','g'),(_,x)=>{blocks.push('<pre><code>'+x+'</code></pre>');return '@@CODE'+(blocks.length-1)+'@@'});s=s.replace(/^(?:[-*+] [^\n]*(?:\n|$))+/gm,items=>{let trailing=items.endsWith('\n'),lines=items.split('\n');if(trailing)lines.pop();return '<ul>'+lines.map(item=>'<li>'+item.slice(2)+'</li>').join('')+'</ul>'+(trailing?'\n':'')}).replace(/^-# (.*)$/gm,'<small class="subtext">$1</small>').replace(new RegExp(tick+'([^'+tick+']+)'+tick,'g'),'<code>$1</code>').replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>').replace(/__([^_]+)__/g,'<strong>$1</strong>').replace(/\*([^*]+)\*/g,'<em>$1</em>').replace(/^###? (.+)$/gm,'<h3>$1</h3>').replace(/^# (.+)$/gm,'<h2>$1</h2>').replace(/^&gt; (.+)$/gm,'<blockquote>$1</blockquote>').replace(/\[([^\]]+)\]\((https?:\/\/[^\s)]+)\)/g,'<a href="$2" target="_blank" rel="noopener noreferrer">$1</a>').replace(/(^|\s)(https?:\/\/[^\s<]+)/g,'$1<a href="$2" target="_blank" rel="noopener noreferrer">$2</a>').replace(/\n/g,'<br>');return s.replace(/@@CODE(\d+)@@/g,(_,i)=>blocks[Number(i)])}
`

export const WEB_JS = String.raw`
const $=s=>document.querySelector(s);let state={session:null,sessionName:'default',promptSessionName:'default',renderedSession:null,historySignatures:new Map(),settingsSignature:'',runs:new Map(),starting:new Set(),loadVersion:0,pollTimer:0,pending:new Set(),modalTarget:null,following:true,unseen:false,scrollFrame:0,scrollTimer:0,autoScrolling:false};
${WEB_MARKDOWN_JS}
function embed(e){let color=Number.isInteger(e.color)?'#'+e.color.toString(16).padStart(6,'0'):'#5865f2';return '<div class="embed" style="border-color:'+color+'">'+(e.author?.name?'<small>'+esc(e.author.name)+'</small>':'')+(e.title?'<h3>'+esc(e.title)+'</h3>':'')+(e.description?'<div>'+md(e.description)+'</div>':'')+(Array.isArray(e.fields)?e.fields.map(f=>'<p><strong>'+esc(f.name)+'</strong><br>'+md(f.value)+'</p>').join(''):'')+(e.footer?.text?'<footer>'+esc(e.footer.text)+'</footer>':'')+'</div>'}
function componentEmoji(e){if(!e||typeof e!=='object')return '';let name=esc(e.name||'');if(e.id&&/^\d+$/.test(String(e.id)))return '<img class="component-emoji" src="https://cdn.discordapp.com/emojis/'+esc(e.id)+'.webp?size=40" alt="'+name+'">';return name?'<span aria-hidden="true">'+name+'</span>':''}
const attr=(name,value)=>value===undefined||value===null?'':' '+name+'="'+esc(value)+'"';
const emoji=c=>c?.emoji?componentEmoji(c.emoji)+' ':'';
const liveId=id=>/^gpt-action:[^:]+:[a-z0-9_-]{1,32}$/.test(id||'');
function buttonComponent(c){let label=emoji(c)+esc(c.label||(!c.emoji?'Action':'')),style=['','primary','secondary','success','danger','link'][c.style]||'secondary',disabled=c.disabled===true;if(c.url){if(disabled)return '<span class="component-button '+style+'" aria-disabled="true">'+label+'</span>';return '<a class="component-button '+style+'" href="'+esc(c.url)+'" target="_blank" rel="noopener noreferrer">'+label+'</a>'}if(!c.custom_id)return fallback(c);let live=liveId(c.custom_id);return '<button type="button" class="component-button '+style+'" data-component-id="'+esc(c.custom_id)+'"'+(disabled||!live?' disabled':'')+(!live?' title="This historical interaction is unavailable"':'')+'>'+label+'</button>'}
function stringSelect(c,modal=false){let min=Number.isInteger(c.min_values)?c.min_values:1,max=Number.isInteger(c.max_values)?c.max_values:1,multiple=max>1?' multiple size="'+Math.min(max,5)+'"':'';let placeholder=c.placeholder||'Make a selection',hasDefault=Array.isArray(c.options)&&c.options.some(o=>o.default);let options=(!hasDefault&&max===1?'<option value="" selected'+(min>0?' disabled':'')+'>'+esc(placeholder)+'</option>':'')+(Array.isArray(c.options)?c.options.map(o=>'<option value="'+esc(o.value)+'"'+(o.default?' selected':'')+'>'+emoji(o)+esc(o.label)+(o.description?' — '+esc(o.description):'')+'</option>').join(''):'');let id=esc(c.custom_id||''),disabled=c.disabled||!modal&&!liveId(c.custom_id),select='<select class="component-select" data-field-type="3" data-min="'+min+'" data-max="'+max+'"'+(modal?' data-modal-field="'+id+'"':' data-select-id="'+id+'"')+multiple+(disabled?' disabled':'')+' aria-label="'+esc(placeholder)+'">'+options+'</select>';return modal?select:'<div class="entity-select">'+select+'<button type="button" class="component-button secondary select-apply" data-component-id="'+id+'"'+(disabled?' disabled':'')+'>Select</button></div>'}
const entityNames={5:'User',6:'Role',7:'Mentionable',8:'Channel'};
function entitySelect(c,modal=false){let min=Number.isInteger(c.min_values)?c.min_values:1,max=Number.isInteger(c.max_values)?c.max_values:1,defaults=Array.isArray(c.default_values)?c.default_values.map(v=>v.id).filter(Boolean).join(', '):'';let id=esc(c.custom_id||''),disabled=c.disabled||!modal&&!liveId(c.custom_id);return '<div class="entity-select"><input type="text" value="'+esc(defaults)+'" placeholder="'+esc(c.placeholder||entityNames[c.type]+' IDs, comma separated')+'" data-field-type="'+c.type+'" data-min="'+min+'" data-max="'+max+'"'+(modal?' data-modal-field="'+id+'"':' data-entity-id="'+id+'"')+(disabled?' disabled':'')+'><button type="button" class="component-button secondary entity-apply" data-component-id="'+id+'"'+(modal||disabled?' disabled':'')+'>Select</button></div>'}
function fallback(c){return '<div class="component-fallback" role="note">Unsupported Discord component'+(Number.isInteger(c?.type)?' (type '+c.type+')':'')+'</div>'}
const componentRenderers={1:c=>'<div class="component-row">'+components(c.components)+'</div>',2:buttonComponent,3:c=>stringSelect(c),5:c=>entitySelect(c),6:c=>entitySelect(c),7:c=>entitySelect(c),8:c=>entitySelect(c),9:c=>'<section>'+components(c.components)+(c.accessory?components([c.accessory]):'')+'</section>',10:c=>typeof c.content==='string'?'<div>'+md(c.content)+'</div>':fallback(c),14:()=>'<hr>',17:c=>'<div class="component-container">'+components(c.components)+'</div>'};
function components(items){if(!Array.isArray(items))return '';return items.map(c=>{if(!c||typeof c!=='object')return '';return(componentRenderers[c.type]||fallback)(c)}).join('')}
function payload(raw){let p=raw;if(typeof raw==='string'){try{p=JSON.parse(raw)}catch{return md(raw)}}if(!p||typeof p!=='object')return '';return(typeof p.content==='string'?md(p.content):'')+(Array.isArray(p.embeds)?p.embeds.map(embed).join(''):'')+components(p.components)}
function message(role,content,time=new Date(),runId,status){let el=document.createElement('article');el.className='message '+role;if(runId)el.dataset.runId=runId;if(status)el.dataset.status=status;el.innerHTML='<span class="avatar">'+(role==='user'?'Y':'S')+'</span><div><div class="meta"><strong>'+(role==='user'?'You':'Solver')+'</strong><time>'+new Date(time).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})+'</time></div><div class="body">'+(role==='assistant'?payload(content):md(content))+'</div></div>';$('#messages').append(el);return el}
const empty=()=>'<div class="empty">No messages yet</div>';
const messages=$('#messages'),bottomThreshold=72;
function nearBottom(){return messages.scrollHeight-messages.scrollTop-messages.clientHeight<=bottomThreshold}
function renderJump(){$('#jump-bottom').hidden=state.following||!state.unseen}
function setFollowing(value){state.following=value;if(value)state.unseen=false;renderJump()}
function stopAutoScroll(){state.autoScrolling=false;clearTimeout(state.scrollTimer)}
function followBottom(behavior='smooth'){if(!state.following)return;cancelAnimationFrame(state.scrollFrame);state.scrollFrame=requestAnimationFrame(()=>{state.autoScrolling=true;messages.scrollTo({top:messages.scrollHeight,behavior});clearTimeout(state.scrollTimer);state.scrollTimer=setTimeout(()=>{state.autoScrolling=false;if(nearBottom())setFollowing(true)},1000)})}
function contentChanged(){if(state.following)followBottom();else{state.unseen=true;renderJump()}}
const resizeObserver='ResizeObserver'in window?new ResizeObserver(contentChanged):null;
new MutationObserver(()=>{messages.querySelectorAll('.body').forEach(body=>resizeObserver?.observe(body));contentChanged()}).observe(messages,{childList:true,subtree:true,characterData:true});
async function api(path,opt={}){opt.headers={...(opt.body?{'Content-Type':'application/json'}:{}),...(state.session?.csrfToken?{'X-CSRF-Token':state.session.csrfToken}:{}),...opt.headers};let r=await fetch(path,opt);if(!r.ok){let m='Request failed';try{m=(await r.json()).error||m}catch{}throw new Error(m)}return r}
async function readUpdates(r,onUpdate){let reader=r.body.getReader(),decoder=new TextDecoder(),buffer='';while(true){let {done,value}=await reader.read();buffer+=decoder.decode(value||new Uint8Array(),{stream:!done});let lines=buffer.split('\n');buffer=lines.pop()||'';for(let line of lines){if(line)onUpdate(JSON.parse(line))}if(done)break}}
async function interaction(target,customId,values=[],fields){if(state.pending.has(customId))return;state.pending.add(customId);let controls=[...(target.querySelectorAll?.('button,select,input')||[])].filter(x=>!x.disabled),status=target.querySelector?.('.interaction-status');if(!status){status=document.createElement('div');status.className='interaction-status status';target.append(status)}status.textContent='Working…';controls.forEach(x=>x.disabled=true);try{let r=await api('/api/chat/interaction',{method:'POST',body:JSON.stringify({customId,values,...(fields?{fields}:{})})}),reader=r.body.getReader(),decoder=new TextDecoder(),buffer='';while(true){let {done,value}=await reader.read();buffer+=decoder.decode(value||new Uint8Array(),{stream:!done});let lines=buffer.split('\n');buffer=lines.pop()||'';for(let line of lines){if(!line)continue;let update=JSON.parse(line);if(update.error)throw new Error(update.error);if(update.modal){openModal(update.modal,target);status.textContent='';continue}if(update.payload){target.innerHTML=payload(update.payload)}}if(done)break}}catch(err){status=target.querySelector?.('.interaction-status')||status;status.className='interaction-status status error';status.textContent=err.message}finally{state.pending.delete(customId);if(target.isConnected)controls.forEach(x=>{if(x.isConnected)x.disabled=false})}}
function modalText(c,label){let common=' data-modal-field="'+esc(c.custom_id)+'" data-field-type="4"'+attr('minlength',c.min_length)+attr('maxlength',c.max_length)+(c.required===false?'':' required')+attr('placeholder',c.placeholder);let input=c.style===2?'<textarea rows="4"'+common+'>'+esc(c.value||'')+'</textarea>':'<input type="text" value="'+esc(c.value||'')+'"'+common+'>';return '<label class="modal-field"><span>'+esc(label||c.label||'Text')+'</span>'+input+'</label>'}
function modalChoices(c,label,type){let options=Array.isArray(c.options)?c.options:[],radio=type===21,min=radio?(c.required===false?0:1):(Number.isInteger(c.min_values)?c.min_values:(c.required===false?0:1)),max=radio?1:(Number.isInteger(c.max_values)?c.max_values:options.length);return '<fieldset class="modal-field" data-modal-field="'+esc(c.custom_id)+'" data-field-type="'+type+'" data-min="'+min+'" data-max="'+max+'"><legend>'+esc(label||c.label||'Choose')+'</legend><div class="modal-options">'+options.map(o=>'<label class="modal-option"><input type="'+(radio?'radio':'checkbox')+'" name="field-'+esc(c.custom_id)+'" value="'+esc(o.value)+'"'+(o.default?' checked':'')+'><span>'+esc(o.label)+(o.description?'<small><br>'+esc(o.description)+'</small>':'')+'</span></label>').join('')+'</div></fieldset>'}
function modalComponent(c,label,description){if(!c||typeof c!=='object')return '';if(c.type===1)return (c.components||[]).map(x=>modalComponent(x)).join('');if(c.type===18)return '<div>'+(description||c.description?'<small>'+esc(description||c.description)+'</small>':'')+modalComponent(c.component,c.label,c.description)+'</div>';if(c.type===10)return '<div>'+md(c.content||'')+'</div>';if(c.type===4)return modalText(c,label);if(c.type===3)return '<label class="modal-field"><span>'+esc(label||c.label||'Choose')+'</span>'+stringSelect(c,true)+'</label>';if(entityNames[c.type])return '<label class="modal-field"><span>'+esc(label||c.label||entityNames[c.type])+'</span>'+entitySelect(c,true)+'</label>';if(c.type===21||c.type===22)return modalChoices(c,label,c.type);if(c.type===23)return '<label class="modal-option modal-field"><input type="checkbox" data-modal-field="'+esc(c.custom_id)+'" data-field-type="23"'+(c.default?' checked':'')+(c.required?' required':'')+'><span>'+esc(label||c.label||'Confirm')+'</span></label>';return fallback(c)}
function openModal(modal,target){let dialog=$('#interaction-modal'),form=$('#interaction-modal-form');state.modalTarget=target;form.dataset.customId=modal.custom_id||'';$('#interaction-modal-title').textContent=modal.title||'Complete form';$('#interaction-modal-fields').innerHTML=(modal.components||[]).map(c=>modalComponent(c)).join('');$('.modal-error').textContent='';dialog.showModal()}
function fieldValues(field){let type=Number(field.dataset.fieldType),custom_id=field.dataset.modalField||field.dataset.componentId||field.dataset.entityId||field.dataset.selectId;if(type===4)return{custom_id,type,value:field.value};if(type===21)return{custom_id,type,value:field.querySelector('input:checked')?.value||null};if(type===23)return{custom_id,type,value:field.checked};if(type===3)return{custom_id,type,values:[...field.selectedOptions].map(o=>o.value).filter(Boolean)};if(entityNames[type])return{custom_id,type,values:field.value.split(',').map(x=>x.trim()).filter(Boolean)};return{custom_id,type,values:[...field.querySelectorAll('input:checked')].map(x=>x.value)}}
function validateField(field,data){let min=Number(field.dataset.min||0),max=Number(field.dataset.max||25),count=data.values?.length;if(Number(field.dataset.fieldType)===21&&!data.value&&min>0)return 'Select one value.';if(count!==undefined&&(count<min||count>max))return 'Select between '+min+' and '+max+' value'+(max===1?'':'s')+'.';return ''}
function controlsDisabled(disabled){['#model-select','#effort','#max-tokens'].forEach(id=>$(id).disabled=disabled)}
function renderRunControls(){let running=state.runs.has(state.sessionName)||state.starting.has(state.sessionName);$('#cancel-run').hidden=!state.runs.has(state.sessionName);$('#cancel-run').disabled=state.starting.has(state.sessionName);controlsDisabled(running)}
function runMessage(runId){return[...messages.querySelectorAll('.assistant[data-run-id]')].find(el=>el.dataset.runId===runId)}
function scheduleSessionPoll(version=state.loadVersion){clearTimeout(state.pollTimer);state.pollTimer=setTimeout(()=>syncSession(version).catch(()=>{if(version===state.loadVersion)scheduleSessionPoll(version)}),1000)}
function renderSessionOptions(sessions){let select=$('#session-select');select.innerHTML=sessions.map(name=>'<option value="'+esc(name)+'">'+esc(name)+'</option>').join('')+'<option value="">+ New session</option>';select.value=state.sessionName}
function renderSessionState(data){renderSessionOptions(data.sessions);state.settingsSignature=JSON.stringify(data.settings);$('#model-select').value=data.settings.model;$('#effort').value=data.settings.effort;$('#max-tokens').value=data.settings.maxTokens;$('#max-tokens-value').value=data.settings.maxTokens}
async function loadModels(){try{let r=await api('/models'),data=await r.json();$('#model-options').innerHTML=(data.models||[]).map(model=>'<option value="'+esc(model)+'"></option>').join('')}catch(e){$('#model-select').title='Could not load models: '+e.message}}
async function history(name=state.sessionName,version=state.loadVersion){let r=await api('/api/chat/history?session='+encodeURIComponent(name)),turns=await r.json();if(name!==state.sessionName||version!==state.loadVersion)return;clearTimeout(state.pollTimer);let active=turns.find(t=>t.role==='assistant'&&t.status==='running'&&t.runId),existing=state.runs.get(name),local=active&&existing?.id===active.runId&&existing.local,signature=JSON.stringify(turns);if(active)state.runs.set(name,{id:active.runId,local:!!local});else state.runs.delete(name);if(state.renderedSession!==name||state.historySignatures.get(name)!==signature){state.renderedSession=name;state.historySignatures.set(name,signature);$('#messages').innerHTML=turns.length?'':empty();turns.forEach(t=>message(t.role,t.content,t.startedAt||new Date(),t.runId,t.status))}renderRunControls();if(!local)scheduleSessionPoll(version)}
async function syncSession(version=state.loadVersion){let r=await api('/api/chat/sessions'),data=await r.json();if(version!==state.loadVersion)return;let name=data.selectedSession;if(name!==state.sessionName){state.sessionName=name;version=++state.loadVersion;renderSessionState(data)}else if(state.settingsSignature!==JSON.stringify(data.settings))renderSessionState(data);else renderSessionOptions(data.sessions);await history(name,version)}
async function session(){let r=await fetch('/api/session');state.session=await r.json();let yes=!!state.session.user,setup=state.session.oidcSetupRequired;$('#auth-view').hidden=yes||setup;$('#chat-view').hidden=!yes;$('#settings-view').hidden=!setup;$('#prompt-settings-view').hidden=true;$('#admin-prompt').hidden=!yes;$('#login').hidden=!state.session.oidcEnabled;$('#setup-notice').hidden=!setup;$('#settings-eyebrow').textContent=setup?'INITIAL SETUP':'ADMINISTRATION';if(setup){$('#settings-form').elements.enabled.checked=true;await settings();return}if(yes){try{let sessions=await api('/api/chat/sessions'),data=await sessions.json();state.sessionName=data.selectedSession;renderSessionState(data);await Promise.all([history(),loadModels()])}catch(e){$('#messages').innerHTML='<div class="empty error">'+esc(e.message)+'</div>';$('#composer').hidden=true}}else if(state.session.automaticLogin&&state.session.oidcEnabled)location.href='/auth/login'}
async function settings(){try{let r=await api('/api/admin/oidc'),data=await r.json(),f=$('#settings-form');Object.entries(data||{}).forEach(([k,v])=>{let field=f.elements.namedItem(k);if(!field)return;if(field.type==='checkbox')field.checked=!!v;else if(k!=='hasClientSecret')field.value=v??''});$('#secret-state').textContent=data?.hasClientSecret?'A secret is stored.':''}catch(e){$('#settings-status').textContent=e.message}}
function renderPromptSetting(data){$('#prompt-settings-form').elements.prompt.value=data.prompt;$('#prompt-metadata').textContent=data.updatedAt?'Last updated '+new Date(data.updatedAt).toLocaleString()+' by '+data.updatedBy:(data.isDefault?'Using built-in default':'')}
function renderSessionPromptSetting(data){$('#session-prompt-settings-form').elements.prompt.value=data.prompt;$('#session-prompt-metadata').textContent=data.updatedAt?'Last updated '+new Date(data.updatedAt).toLocaleString()+' by '+data.updatedBy:'No session-specific prompt is set.'}
async function openPromptSettings(){try{state.promptSessionName=state.sessionName;let [globalResponse,sessionResponse]=await Promise.all([api('/api/admin/system-prompt'),api('/api/chat/system-prompt?session='+encodeURIComponent(state.promptSessionName))]),globalPrompt=await globalResponse.json(),sessionPrompt=await sessionResponse.json();renderPromptSetting(globalPrompt);renderSessionPromptSetting(sessionPrompt);$('#session-prompt-name').textContent=state.promptSessionName;$('#chat-view').hidden=true;$('#prompt-settings-view').hidden=false;$('#prompt-settings-status').textContent='';$('#session-prompt-settings-status').textContent=''}catch(e){$('#messages').innerHTML='<div class="empty error">'+esc(e.message)+'</div>'}}
$('#messages').addEventListener('click',e=>{let button=e.target.closest('button[data-component-id]');if(!button||button.disabled)return;let target=button.closest('.body');if(button.classList.contains('entity-apply')||button.classList.contains('select-apply')){let input=button.previousElementSibling,data=fieldValues(input),error=validateField(input,data);if(error){let status=target.querySelector('.interaction-status')||document.createElement('div');status.className='interaction-status status error';status.textContent=error;if(!status.isConnected)target.append(status);return}interaction(target,button.dataset.componentId,data.values);return}interaction(target,button.dataset.componentId)});
messages.addEventListener('scroll',()=>{if(!state.autoScrolling)setFollowing(nearBottom())},{passive:true});messages.addEventListener('scrollend',()=>{stopAutoScroll();setFollowing(nearBottom())});messages.addEventListener('wheel',stopAutoScroll,{passive:true});messages.addEventListener('touchstart',stopAutoScroll,{passive:true});messages.addEventListener('pointerdown',stopAutoScroll,{passive:true});document.addEventListener('keydown',e=>{if(['PageUp','PageDown','Home','End','ArrowUp','ArrowDown',' '].includes(e.key))stopAutoScroll()});$('#jump-bottom').onclick=()=>{setFollowing(true);followBottom()};
$('.modal-close').onclick=$('.modal-cancel').onclick=()=>$('#interaction-modal').close();
$('#interaction-modal-form').addEventListener('submit',e=>{e.preventDefault();let form=e.target,error=$('.modal-error');if(!form.reportValidity())return;let fields=[...form.querySelectorAll('[data-modal-field]')].filter(x=>!x.closest('[data-modal-field]')||x.closest('[data-modal-field]')===x),data=fields.map(fieldValues);for(let i=0;i<fields.length;i++){let problem=validateField(fields[i],data[i]);if(problem){error.textContent=problem;return}}let customId=form.dataset.customId,target=state.modalTarget;$('#interaction-modal').close();interaction(target,customId,[],data)});
$('#session-select').addEventListener('change',async e=>{let previous=state.sessionName,name=e.target.value;clearTimeout(state.pollTimer);if(!name){name=(window.prompt('New session name')||'').trim();if(!name){e.target.value=previous;scheduleSessionPoll();return}if(name.length>100){window.alert('Session name must not exceed 100 characters.');e.target.value=previous;scheduleSessionPoll();return}}let version=++state.loadVersion;state.sessionName=name;renderRunControls();try{let r=await api('/api/chat/sessions',{method:'POST',body:JSON.stringify({sessionName:name})}),data=await r.json();if(version!==state.loadVersion||name!==state.sessionName)return;renderSessionState(data);await history(name,version)}catch(err){if(version!==state.loadVersion)return;state.sessionName=previous;state.loadVersion++;e.target.value=previous;scheduleSessionPoll();window.alert(err.message)}finally{renderRunControls()}});
$('#max-tokens').addEventListener('input',e=>$('#max-tokens-value').value=e.target.value);
async function cancelRun(name=state.sessionName,refresh=true){let run=state.runs.get(name);if(!run)return false;$('#cancel-run').disabled=true;try{await api('/api/chat/cancel',{method:'POST',body:JSON.stringify({sessionName:name,runId:run.id})});if(state.runs.get(name)?.id===run.id)state.runs.delete(name);if(refresh&&name===state.sessionName)await history(name,state.loadVersion);return true}finally{renderRunControls()}}
async function sendPrompt(prompt,name,settings){if(state.starting.has(name))return;clearTimeout(state.pollTimer);state.starting.add(name);renderRunControls();let pending,runId,failed=false;try{if(state.runs.has(name))await cancelRun(name,true);if(name===state.sessionName){state.historySignatures.delete(name);$('#messages .empty')?.remove();message('user',prompt);pending=message('assistant','');pending.querySelector('.body').innerHTML='<span class="status">Starting assistant...</span>'}let body={prompt,sessionName:name,...settings},r=await api('/api/chat',{method:'POST',body:JSON.stringify(body)}),reader=r.body.getReader(),decoder=new TextDecoder(),buffer='';while(true){let {done,value}=await reader.read();buffer+=decoder.decode(value||new Uint8Array(),{stream:!done});let lines=buffer.split('\n');buffer=lines.pop()||'';for(let line of lines){if(!line)continue;let update=JSON.parse(line);if(update.runId){runId=update.runId;state.runs.set(name,{id:runId,local:true});state.starting.delete(name);if(pending)pending.dataset.runId=runId;renderRunControls()}let target=runId&&name===state.sessionName&&state.runs.get(name)?.id===runId?(runMessage(runId)||pending):null;if(target&&update.payload)target.querySelector('.body').innerHTML=payload(update.payload);if(target&&update.error)target.querySelector('.body').innerHTML='<span class="status error">'+esc(update.error)+'</span>'}if(done)break}}catch(err){failed=true;let target=runId?runMessage(runId):pending;if(name===state.sessionName&&target?.isConnected)target.querySelector('.body').innerHTML='<span class="status error">'+esc(err.message)+'</span>'}finally{state.starting.delete(name);if(runId&&state.runs.get(name)?.id===runId)state.runs.delete(name);let target=runId&&runMessage(runId);if(target)delete target.dataset.runId;if(pending)delete pending.dataset.runId;if(failed&&name===state.sessionName)await history(name,state.loadVersion).catch(()=>{});if(name===state.sessionName)scheduleSessionPoll();renderRunControls()}}
$('#cancel-run').onclick=async()=>{try{await cancelRun()}catch(err){window.alert(err.message)}};
$('#composer').addEventListener('submit',async e=>{e.preventDefault();let name=state.sessionName;if(state.starting.has(name))return;let prompt=$('#prompt').value.trim();if(!prompt)return;let settings={model:$('#model-select').value.trim(),effort:$('#effort').value,maxTokens:Number($('#max-tokens').value)};$('#prompt').value='';$('#prompt').style.height='auto';if(prompt==='/clear'){try{state.starting.add(name);renderRunControls();await api('/api/chat/clear',{method:'POST',body:JSON.stringify({sessionName:name})});state.runs.delete(name);await history(name,state.loadVersion)}catch(err){$('#messages').innerHTML='<div class="empty error">'+esc(err.message)+'</div>'}finally{state.starting.delete(name);renderRunControls()}return}await sendPrompt(prompt,name,settings)});
$('#prompt').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();$('#composer').requestSubmit()}});$('#prompt').addEventListener('input',e=>{e.target.style.height='auto';e.target.style.height=Math.min(e.target.scrollHeight,180)+'px'});$('#login').onclick=()=>location.href='/auth/login';
$('#admin-prompt').onclick=openPromptSettings;$('#prompt-back').onclick=()=>{$('#prompt-settings-view').hidden=true;$('#chat-view').hidden=false};
$('#prompt-settings-form').addEventListener('submit',async e=>{e.preventDefault();try{let prompt=e.target.elements.prompt.value,r=await api('/api/admin/system-prompt',{method:'PUT',body:JSON.stringify({prompt})}),data=await r.json();renderPromptSetting(data);$('#prompt-settings-status').textContent='Saved'}catch(err){$('#prompt-settings-status').textContent=err.message}});
$('#prompt-reset').onclick=async()=>{try{let r=await api('/api/admin/system-prompt/reset',{method:'POST'}),data=await r.json();renderPromptSetting(data);$('#prompt-settings-status').textContent='Reset to default'}catch(err){$('#prompt-settings-status').textContent=err.message}};
$('#session-prompt-settings-form').addEventListener('submit',async e=>{e.preventDefault();try{let prompt=e.target.elements.prompt.value,r=await api('/api/chat/system-prompt',{method:'PUT',body:JSON.stringify({sessionName:state.promptSessionName,prompt})}),data=await r.json();renderSessionPromptSetting(data);$('#session-prompt-settings-status').textContent='Saved'}catch(err){$('#session-prompt-settings-status').textContent=err.message}});
$('#session-prompt-reset').onclick=async()=>{try{let r=await api('/api/chat/system-prompt/reset',{method:'POST',body:JSON.stringify({sessionName:state.promptSessionName})}),data=await r.json();renderSessionPromptSetting(data);$('#session-prompt-settings-status').textContent='Removed'}catch(err){$('#session-prompt-settings-status').textContent=err.message}};
$('#settings-form').addEventListener('submit',async e=>{e.preventDefault();let f=e.target,data=Object.fromEntries(new FormData(f));data.enabled=f.elements.enabled.checked;data.automaticLogin=f.elements.automaticLogin.checked;try{let r=await api('/api/admin/oidc',{method:'PUT',body:JSON.stringify(data)}),saved=await r.json();$('#settings-status').textContent='Saved';$('#secret-state').textContent=saved.hasClientSecret?'A secret is stored.':'';if(state.session.oidcSetupRequired)await session()}catch(err){$('#settings-status').textContent=err.message}});session().catch(e=>$('#auth-error').textContent=e.message);
`
